export const TIPS = [
  "输入 {highlight}@{/highlight} 后跟文件名，可模糊搜索并附加文件到提示词。",
  "以 {highlight}!{/highlight} 开头可直接运行 Shell 命令（例如 {highlight}!ls -la{/highlight}）。",
  "按 {highlight}Tab{/highlight} 在 Build（完全访问）和 Plan（只读）Agent 之间切换。",
  "使用 {highlight}/undo{/highlight} 撤销上一条消息及 MemFit 所做的文件修改。",
  "使用 {highlight}/redo{/highlight} 恢复已撤销的消息和文件修改。",
  "运行 {highlight}/share{/highlight} 在 memfit.ai 创建会话的公开链接。",
  "将图片拖放到终端，即可作为提示词的上下文。",
  "按 {highlight}Ctrl+V{/highlight} 直接从剪贴板粘贴图片到提示词。",
  "按 {highlight}Ctrl+X E{/highlight} 或 {highlight}/editor{/highlight} 在外部编辑器中编写消息。",
  "运行 {highlight}/init{/highlight} 根据代码库结构自动生成项目规则。",
  "运行 {highlight}/models{/highlight} 或 {highlight}Ctrl+X M{/highlight} 查看并切换可用的 AI 模型。",
  "使用 {highlight}/theme{/highlight} 或 {highlight}Ctrl+X T{/highlight} 预览并切换 50+ 内置主题。",
  "按 {highlight}Ctrl+X N{/highlight} 或 {highlight}/new{/highlight} 开始新会话。",
  "使用 {highlight}/sessions{/highlight} 或 {highlight}Ctrl+X L{/highlight} 列出并继续之前的对话。",
  "运行 {highlight}/compact{/highlight} 在接近上下文限制时压缩长会话。",
  "按 {highlight}Ctrl+X X{/highlight} 或 {highlight}/export{/highlight} 将对话导出为 Markdown。",
  "按 {highlight}Ctrl+X Y{/highlight} 复制助手的上一条消息到剪贴板。",
  "按 {highlight}Ctrl+P{/highlight} 查看所有可用操作和命令。",
  "运行 {highlight}/connect{/highlight} 添加 75+ 支持的 LLM 提供商的 API 密钥。",
  "默认 leader 键是 {highlight}Ctrl+X{/highlight}；与其他键组合可快速操作。",
  "按 {highlight}F2{/highlight} 快速切换最近使用的模型。",
  "按 {highlight}Ctrl+X B{/highlight} 显示/隐藏侧边栏面板。",
  "使用 {highlight}PageUp{/highlight}/{highlight}PageDown{/highlight} 在对话历史中导航。",
  "按 {highlight}Ctrl+G{/highlight} 或 {highlight}Home{/highlight} 跳到对话开头。",
  "按 {highlight}Ctrl+Alt+G{/highlight} 或 {highlight}End{/highlight} 跳到最新消息。",
  "按 {highlight}Shift+Enter{/highlight} 或 {highlight}Ctrl+J{/highlight} 在提示词中添加换行。",
  "输入时按 {highlight}Ctrl+C{/highlight} 清空输入框。",
  "按 {highlight}Escape{/highlight} 停止 AI 响应。",
  "切换到 {highlight}Plan{/highlight} Agent 可获取建议而不实际修改代码。",
  "在提示词中使用 {highlight}@<agent-name>{/highlight} 调用专用子 Agent。",
  "按 {highlight}Ctrl+X Right/Left{/highlight} 在父会话和子会话之间切换。",
  "在项目根目录创建 {highlight}memfit.json{/highlight} 进行项目级设置。",
  "将设置放在 {highlight}~/.config/memfit/memfit.json{/highlight} 进行全局配置。",
  "在配置中添加 {highlight}$schema{/highlight} 可在编辑器中获得自动补全。",
  "在配置中设置 {highlight}model{/highlight} 指定默认模型。",
  "通过配置的 {highlight}keybinds{/highlight} 部分覆盖任意快捷键。",
  "将任意快捷键设为 {highlight}none{/highlight} 可完全禁用。",
  "在配置的 {highlight}mcp{/highlight} 部分配置本地或远程 MCP 服务器。",
  "MemFit 自动处理需要认证的远程 MCP 服务器的 OAuth。",
  "在 {highlight}.memfit/command/{/highlight} 添加 {highlight}.md{/highlight} 文件定义可复用的自定义提示。",
  "在自定义命令中使用 {highlight}$ARGUMENTS{/highlight}、{highlight}$1{/highlight}、{highlight}$2{/highlight} 接收动态输入。",
  "在命令中使用反引号注入 Shell 输出（例如 {highlight}`git status`{/highlight}）。",
  "在 {highlight}.memfit/agent/{/highlight} 添加 {highlight}.md{/highlight} 文件定义专用 AI 角色。",
  "为每个 Agent 配置 {highlight}edit{/highlight}、{highlight}bash{/highlight} 和 {highlight}webfetch{/highlight} 工具的权限。",
  '使用模式如 {highlight}"git *": "allow"{/highlight} 实现细粒度 bash 权限。',
  '设置 {highlight}"rm -rf *": "deny"{/highlight} 阻止破坏性命令。',
  '配置 {highlight}"git push": "ask"{/highlight} 在推送前要求审批。',
  "MemFit 使用 prettier、gofmt、ruff 等自动格式化文件。",
  '在配置中设置 {highlight}"formatter": false{/highlight} 禁用所有自动格式化。',
  "在配置中定义带文件扩展名的自定义格式化命令。",
  "MemFit 使用 LSP 服务器进行智能代码分析。",
  "在 {highlight}.memfit/tool/{/highlight} 创建 {highlight}.ts{/highlight} 文件定义新的 LLM 工具。",
  "工具定义可以调用 Python、Go 等语言编写的脚本。",
  "在 {highlight}.memfit/plugin/{/highlight} 添加 {highlight}.ts{/highlight} 文件作为事件钩子。",
  "使用插件在会话完成时发送系统通知。",
  "创建插件阻止 MemFit 读取敏感文件。",
  "使用 {highlight}memfit run{/highlight} 进行非交互式脚本化使用。",
  "使用 {highlight}memfit run --continue{/highlight} 恢复上次会话。",
  "使用 {highlight}memfit run -f file.ts{/highlight} 通过 CLI 附加文件。",
  "使用 {highlight}--format json{/highlight} 在脚本中获得机器可读输出。",
  "运行 {highlight}memfit serve{/highlight} 进行无头 API 访问。",
  "使用 {highlight}memfit run --attach{/highlight} 连接到运行中的服务器以加速运行。",
  "运行 {highlight}memfit upgrade{/highlight} 更新到最新版本。",
  "运行 {highlight}memfit auth list{/highlight} 查看所有已配置的提供商。",
  "运行 {highlight}memfit agent create{/highlight} 进行引导式 Agent 创建。",
  "在 GitHub Issues/PR 中使用 {highlight}/memfit{/highlight} 触发 AI 操作。",
  "运行 {highlight}memfit github install{/highlight} 设置 GitHub 工作流。",
  "在 Issue 中评论 {highlight}/memfit fix this{/highlight} 自动创建 PR。",
  "在 PR 代码行评论 {highlight}/oc{/highlight} 进行针对性代码审查。",
  '使用 {highlight}"theme": "system"{/highlight} 匹配终端颜色。',
  "在 {highlight}.memfit/themes/{/highlight} 目录创建 JSON 主题文件。",
  "主题支持两种模式的深色/浅色变体。",
  "在自定义主题中引用 ANSI 颜色 0-255。",
  "使用 {highlight}{env:VAR_NAME}{/highlight} 语法在配置中引用环境变量。",
  "使用 {highlight}{file:path}{/highlight} 在配置值中包含文件内容。",
  "在配置中使用 {highlight}instructions{/highlight} 加载额外的规则文件。",
  "将 Agent {highlight}temperature{/highlight} 从 0.0（专注）设置到 1.0（创意）。",
  "配置 {highlight}maxSteps{/highlight} 限制每次请求的 Agent 迭代次数。",
  '设置 {highlight}"tools": {"bash": false}{/highlight} 禁用特定工具。',
  '使用 {highlight}"mcp_*": false{/highlight} 禁用 MCP 服务器的所有工具。',
  "在每个 Agent 配置中覆盖全局工具设置。",
  '设置 {highlight}"share": "auto"{/highlight} 自动分享所有会话。',
  '设置 {highlight}"share": "disabled"{/highlight} 阻止任何会话分享。',
  "运行 {highlight}/unshare{/highlight} 从公开访问中移除会话。",
  "权限 {highlight}doom_loop{/highlight} 防止无限工具调用循环。",
  "权限 {highlight}external_directory{/highlight} 保护项目外的文件。",
  "运行 {highlight}memfit debug config{/highlight} 排查配置问题。",
  "使用 {highlight}--print-logs{/highlight} 标志在 stderr 查看详细日志。",
  "按 {highlight}Ctrl+X G{/highlight} 或 {highlight}/timeline{/highlight} 跳转到特定消息。",
  "按 {highlight}Ctrl+X H{/highlight} 切换消息中代码块的可见性。",
  "按 {highlight}Ctrl+X S{/highlight} 或 {highlight}/status{/highlight} 查看系统状态信息。",
  "启用 {highlight}tui.scroll_acceleration{/highlight} 获得平滑的 macOS 风格滚动。",
  "通过命令面板（{highlight}Ctrl+P{/highlight}）切换聊天中的用户名显示。",
  "运行 {highlight}docker run -it --rm ghcr.io/anomalyco/memfit{/highlight} 进行容器化使用。",
  "使用 {highlight}/connect{/highlight} 连接 MemFit 精选、经过测试的模型。",
  "将项目的 {highlight}AGENTS.md{/highlight} 文件提交到 Git 以便团队共享。",
  "使用 {highlight}/review{/highlight} 审查未提交的更改、分支或 PR。",
  "运行 {highlight}/help{/highlight} 或 {highlight}Ctrl+X H{/highlight} 显示帮助对话框。",
  "使用 {highlight}/details{/highlight} 切换工具执行细节的可见性。",
  "使用 {highlight}/rename{/highlight} 重命名当前会话。",
  "按 {highlight}Ctrl+Z{/highlight} 挂起终端并返回 Shell。",
]
